server:
  port: 8091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端⼝,随意指定⼀个未使⽤的端⼝即可
        dashboard: localhost:8080 # 指定控制台服务的地址
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: jsw
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false # 让nacos把它当成⼀个URL，⽽不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 # 采样的百分⽐
feign:
  sentinel:
    enabled: true